### ISSUE TITLE
Collation utf8_bin is not portable and breaks @Column annotation

### ISSUE THREAD

**Issue by mrblur** [PUGX/shortid-doctrine#7] opened 2020-07-21 14:39 UTC
For instance, Postgres by default does not know this collation and fails with:
```
SQLSTATE[42704]: Undefined object: 7 ERROR:  collation "utf8_bin" for encoding "UTF8" does not exist `.
```

By default it does accept `C.UTF-8` or... `default`.

By hardcoding this value, you limit use cases to MySQL with imposed collation and break Doctrine's `@Column` `collation` support.

Specifing `collation` in `@Column` renders invalid SQL
```php
/**
 * @ORM\Column(type="shortid", options={"collation": "C.UTF-8"})
 */
```

renders SQL like that:

```sql
CHAR(7) COLLATE "utf8_bin" NOT NULL COLLATE "C.UTF-8"
```

As a short-term workaround, it's possible to prepend migration with:
```sql
CREATE COLLATION IF NOT EXISTS utf8_bin FROM "C.UTF-8";
```
But this solution breaks migrations atomicity.

**Comment by garak** [comment] 2020-07-21 14:46
I guess that we can remove collation, or at least make it optional.

**Comment by garak** [comment] 2020-07-28 12:53
Do you think related PR can solve?

**Comment by mrblur** [comment] 2020-07-29 13:42
It solves for mine environment, to be 100% sure, one should verify also with MySQL.
On postgres it generates valid code and respects collation setting.
👍

**Comment by garak** [comment] 2020-07-29 13:52
Fixed and released in v0.6.0

**Closed as completed by garak** 2020-07-29 13:52 UTC

**Comment by c33s** [comment] 2020-08-10 11:10
@garak please reopen. why the forced collation at all? isn't this a simple string value to store? please make it configurable or extend your type from string type. is there a special reason for using `utf8_bin`? this breaks the usage for shortids on sqlite.

**Comment by garak** [comment] 2020-08-10 12:53
Sqlite should be unaffected, since last change restricted utf8_bin to mysql.
I can't recall the reason for such choice, I guess it was performance-related.

**Comment by c33s** [comment] 2020-08-10 13:18
oh, after again having a look at the code, i see you are right (i have overlooked the `!`). my problem was that shortid-bundle installed 0.5.0 and is not "compatible" with 0.6.0  but i simply dropped the bundle and the doctrine type and made my own doctrine type.

but still i think the code is risky and can have unexpected behaviors. as you still hardcode the value for mysql which overrides the annotation. even if it has performance reasons, shouldn't it be configurable and be up to the user if enabled or not? default can of course be on.

**Comment by garak** [comment] 2020-08-10 13:20
I agree that a configurable option is better than an hard coded one. Feel free to open a PR
